name: ProjectFun
main: src.nomarthehero.projectfun.ProjectFun
version: 1.6
commands:
  slap:
    description: Slap somebody
    usage: /slap <player>
    permission: projectfun.slap
    permission-message: Missing permission.
  hug:
    description: Hug somebody
    usage: /hug <player>
    permission: projectfun.hug
    permission-message: Missing permission.
  lick:
    description: Lick somebody
    usage: /lick <player>
    permission: projectfun.lick
    permission-message: Missing permission.
  rekt:
    description: Rek somebody like the Call of Duty kids would
    usage: /rek <player>
    permission: projectfun.rekt
    permission-message: Missing permission.
  rainbow:
    description: Turn rainbow mode on/off
    usage: /rainbow
    permission: projectfun.rainbow
    permission-message: Missing permission.
  rage:
    description: Rage to death
    usage: /rage
    permission: projectfun.rage
    permission-message: Missing permission.
  fun:
    description: Base command
    usage: /fun
    permission: projectfun.fun
    permission-message: Missing permission.